### ISSUE TITLE
Name changes!

### ISSUE THREAD

**Issue by phmayo** [KSP-SpaceDock/KerbalStuff#4]
We need to change KerbalStuff to SpaceDock ASAP.

**Comment by GenPage** [comment]
Changes started in PR #5

**Comment by ThomasKerman** [comment]
I'm actually putting all references to KerbalStuff and it's URL's into the config file in the past hours, so that should be fixed soon. :)

To not break my PR, I will revert commit https://github.com/KSP-SpaceDock/KerbalStuff/commit/edf9982b1299137b67f5fec4452964a8fa0ad22c because this edits stuff I edited too, I don't want to have a messed up code.

**Comment by ThomasKerman** [comment]
Done with #6 

Closing
